title: Blog Bibliotheks- und Archivinformatik
author: Lukas
email: lukas.temperli@stud.fhgr.ch
description: > # this means to ignore newlines
  Vorlage für ein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2024

# social links
twitter_username: nö # DO NOT include the @ character, or else the build will fail!
github_username:  Luigi-Thomas # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
